# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pynifalcon', [dirname(__file__)])
        except ImportError:
            import _pynifalcon
            return _pynifalcon
        if fp is not None:
            try:
                _mod = imp.load_module('_pynifalcon', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pynifalcon = swig_import_helper()
    del swig_import_helper
else:
    import _pynifalcon
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class FalconVec3d(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FalconVec3d, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FalconVec3d, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _pynifalcon.FalconVec3d_x_set
    __swig_getmethods__["x"] = _pynifalcon.FalconVec3d_x_get
    if _newclass:x = _swig_property(_pynifalcon.FalconVec3d_x_get, _pynifalcon.FalconVec3d_x_set)
    __swig_setmethods__["y"] = _pynifalcon.FalconVec3d_y_set
    __swig_getmethods__["y"] = _pynifalcon.FalconVec3d_y_get
    if _newclass:y = _swig_property(_pynifalcon.FalconVec3d_y_get, _pynifalcon.FalconVec3d_y_set)
    __swig_setmethods__["z"] = _pynifalcon.FalconVec3d_z_set
    __swig_getmethods__["z"] = _pynifalcon.FalconVec3d_z_get
    if _newclass:z = _swig_property(_pynifalcon.FalconVec3d_z_get, _pynifalcon.FalconVec3d_z_set)
    def __init__(self): 
        this = _pynifalcon.new_FalconVec3d()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pynifalcon.delete_FalconVec3d
    __del__ = lambda self : None;
FalconVec3d_swigregister = _pynifalcon.FalconVec3d_swigregister
FalconVec3d_swigregister(FalconVec3d)

class FalconDeviceBridge(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FalconDeviceBridge, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FalconDeviceBridge, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pynifalcon.new_FalconDeviceBridge()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pynifalcon.delete_FalconDeviceBridge
    __del__ = lambda self : None;
    def getCount(self): return _pynifalcon.FalconDeviceBridge_getCount(self)
    def open(self, *args): return _pynifalcon.FalconDeviceBridge_open(self, *args)
    def close(self): return _pynifalcon.FalconDeviceBridge_close(self)
    def runIOLoop(self, *args): return _pynifalcon.FalconDeviceBridge_runIOLoop(self, *args)
    def getRawOutput(self): return _pynifalcon.FalconDeviceBridge_getRawOutput(self)
    def setRawInput(self, *args): return _pynifalcon.FalconDeviceBridge_setRawInput(self, *args)
    def loadFirmware(self): return _pynifalcon.FalconDeviceBridge_loadFirmware(self)
    def getErrorCode(self): return _pynifalcon.FalconDeviceBridge_getErrorCode(self)
    def setForces(self, *args): return _pynifalcon.FalconDeviceBridge_setForces(self, *args)
    def getPosition(self): return _pynifalcon.FalconDeviceBridge_getPosition(self)
    def setLEDStatus(self, *args): return _pynifalcon.FalconDeviceBridge_setLEDStatus(self, *args)
FalconDeviceBridge_swigregister = _pynifalcon.FalconDeviceBridge_swigregister
FalconDeviceBridge_swigregister(FalconDeviceBridge)

# This file is compatible with both classic and new-style classes.


